---
Slide: # Dark2
        Count: 4
        Name: 
                - hu_brain_001
                - hu_brain_002
                - hu_brain_003
                - hu_brain_004
        Color:
                - "#1B9E77"
                - "#D95F02"
                - "#7570B3"
                - "#E7298A"
Sample: # Accent
        Count: 5
        Name:
                - "74"
                - "77"
                - 73-1
                - Cortex_29
                - Hippocampus_84
        Color: 
                - "#7FC97F"
                - "#BEAED4"
                - "#FDC086"
                - "#FFFF99"
                - "#386CB0"
Region: # Set1
        Count: 2
        Name:
                - Cortex
                - Hippocampus
        Color:
                - "#E41A1C"
                - "#377EB8"
Segment:
        Count: 5
        Name:
                - Neuron
                - Iba1
                - GFAP
                - Neuropil
                - Full
        Color:
                - magenta
                - gold
                - cyan
                - indianred2
                - chartreuse1
QCparam:
        SegmentQC:
                minSegmentReads: 1000 # Minimum number of reads (1000)
                percentTrimmed: 80    # Minimum % of reads trimmed (80%)
                percentStitched: 80   # Minimum % of reads stitched (80%)
                percentAligned: 75    # Minimum % of reads aligned (80%)
                percentSaturation: 50 # Minimum sequencing saturation (50%)
                minNegativeCount: 1   # Minimum negative control counts (10)
                maxNTCCount: 9000     # Maximum counts observed in NTC well (1000)
                minNuclei: 20         # Minimum # of nuclei estimated (100)
                minArea: 1000         # Minimum segment area (5000)
        Wrap:
                segmentQC_colBy: Segment
                segmentQC_rowBy: Slide
        ProbeQC:
                minProbeRatio: 0.1    # geometric mean of that probe’s counts from all segments divided by the geometric mean of all probe counts representing the target from all segments is less than 0.1
                percentFailGrubbs: 20 # the probe is an outlier according to the Grubb’s test in at least 20% of the segments
        LOQ:
                loqCutoff: 2
                loqMin: 2
        DetectionRate:
                geneDetectionRateThre: 0.05 # Nanostring recommended 5% or 10%
        DerectionRateBins:
                geneDetectionRate: [0, 0.01, 0.05, 0.1, 0.15, 1] # 1%, 5%, 10%, 15%, >15%
                geneDetectionRateLabel: ["<1%", "1-5%", "5-10%", "10-15%", ">15%"]
